name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
      - '!release'
  pull_request:
    branches:
      - 'develop'
      - 'release'

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build TP-HomeAssistant Windows x86
      run: dotnet publish --configuration Release --no-restore TP-HomeAssistant/TP-HomeAssistant.csproj -o package/win-x86/TP-HomeAssistant/ -r win-x86
    - name: Build TP-HomeAssistant MacOSX x64
      run: dotnet publish --configuration Release --no-restore TP-HomeAssistant/TP-HomeAssistant.csproj -o package/osx-x64/TP-HomeAssistant/ -r osx-x64
    - name: Upload Artifact Windows x86
      uses: actions/upload-artifact@v2
      with:
        name: build-win-x86
        path: package/win-x86/TP-HomeAssistant
    - name: Upload Artifact MacOSX x64
      uses: actions/upload-artifact@v2
      with:
        name: build-osx-x64
        path: package/osx-x64/TP-HomeAssistant